# The URL the site will be built for
base_url = "https://blog.munish.me"

# Theme - Radion: A sleek, modern blog theme
theme = "radion"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

# Required taxonomies for radion theme
taxonomies = [
    {name = "categories", feed = true},
    {name = "tags", feed = true},
]

[search]
index_format = "elasticlunr_json"

[markdown]
# Whether to do syntax highlighting
# Theme can be customized by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "one-dark"

[extra]
# Radion theme configuration
radion_title = "Munish Mummadi"
radion_menu = [
    {url = "$BASE_URL", name = "Home"},
    {url = "$BASE_URL/pages/about/", name = "About"},
    {url = "$BASE_URL/categories", name = "Categories"},
    {url = "$BASE_URL/tags", name = "Tags"},
]

# Author information
author = "Munish Mummadi"

# Theme options
theme = "toggle"  # Options: light, dark, auto, toggle
enable_search = true
codeblock = true
favicon = true

# Comments (Giscus) - disabled for now, can be configured later
comments = false
# giscus_repo = "your-github-username/your-repo"
# giscus_repo_id = "FILL_ME_IN"
# giscus_data_category_id = "FILL_ME_IN"

