name: Build and Deploy Zola Site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Rust (needed for Zola)
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install Zola
        run: |
            ZOLA_VERSION="0.21.0"
            curl -sL -o zola.tar.gz "https://github.com/getzola/zola/releases/download/v${ZOLA_VERSION}/zola-v${ZOLA_VERSION}-x86_64-unknown-linux-gnu.tar.gz"
            tar -xzf zola.tar.gz
            sudo mv zola /usr/local/bin/
            zola --version

      - name: Build site with Zola
        run: zola build

      - name: Upload public directory as artifact
        uses: actions/upload-artifact@v4
        with:
          name: public
          path: public